import type { Metadata } from "next";
import { Comfortaa, Varela_Round } from "next/font/google";
import "./globals.css";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin", "vietnamese"],
  weight: ["300", "400", "500", "600", "700"],
});

const varelaRound = Varela_Round({
  variable: "--font-varela-round",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import BottomNav from "@/components/layout/BottomNav";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="vi"
      className={`${comfortaa.variable} ${varelaRound.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-varela-round bg-white">
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
